#+TITLE: Python: Beauty & Chaos
#+AUTHOR: Thomas Vest Nielsen
#+OPTIONS: toc:nil
#+REVEAL_THEME: night



* Hvorfor??
- Kraftfuldt
- Multi-paradigme
- Interpreted
- Populært
- Pseudocode?

* Udviklingsmiljø
- Stort set alle systemer
- IDE (PyCharm, VS, Eclipse)
- Editor (Emacs, Sublime Text, Atom, VS Code)
- På næsten alle unix systemer som standard

* Basic Syntax
- import = Using
- print = Console.WriteLine
- input
- Variabler == type svage
- Standard aritmetik = +, -, *, /, %, **, //


** Syntax Fortsat
- Kommentarer
- Multi-line
- Embedding strings i outputs = %s
- Printe en string flere gange? Ja da

** Lister
- []
- type fri
- append, insert, remove, del
- sort, reverse
- Kombinér lister
- len, max, min

** Tuples
- Værdier kan ikke ændres
- Kan konvertere til liste
- Konvertér liste til tuple

** Dictionary/Map
- key:value pair
- {}
- .keys, .values

** Conditionals
- if
- for (i datasæt eller range)
- while

* Hvad med mine klasser??
- Funktioner
- Klasser
- Properties
- Constructors
- classmethod & staticmethod

* Filer?
- open("file.txt", "wb")
- write(bytes("blabla", 'UTF-8'))
- close()
- reading and writing == open("test.txt", "r+")
- read()
- os.remove()


* Eksempler
- Det er vist på tide!

** Basics
#+BEGIN_SRC python
import random, string

vowels='aeiouy'
consonants='bcdfghjklmnpqrstvwxz'
letters=string.ascii_lowercase

letter_input_1=input("What letter do you want? Enter 'v' for vowels, 'c' for consonants, 'l' for any letter: ")

def generator():
    if letter_input_1=='v':
        letter1=random.choice(vowels)
    elif letter_input_1=='c':
        letter1=random.choice(consonants)
    elif letter_input_1=='l':
        letter1=random.choice(letters)
    else:
        letter1=letter_input_1

    ...
    name=letter1+letter2+letter3
    return(name)

for i in range(20):
    print(generator())

#+END_SRC

** Klasse
#+BEGIN_SRC python
class Animal:
    # None signifies the lack of a value
    # You can make a variable private by starting it with __
    __name = None
    __height = None
    __weight = None
    __sound = None
 
    # The constructor is called to set up or initialize an object
    # self allows an object to refer to itself inside of the class
    def __init__(self, name, height, weight, sound):
        self.__name = name
        self.__height = height
        self.__weight = weight
        self.__sound = sound
 
    def set_name(self, name):
        self.__name = name

    def get_name(self):
        return self.__name

    def toString(self):
        return "{} is {} cm tall and {} kilograms and says {}".format(self.__name, self.__height, self.__weight, self.__sound)

#+END_SRC

** Inheritance
#+BEGIN_SRC python
class Dog(Animal):
    __owner = None
 
    def __init__(self, name, height, weight, sound, owner):
        self.__owner = owner
        self.__animal_type = None
 
        # How to call the super class constructor
        super(Dog, self).__init__(name, height, weight, sound)
 
    def set_owner(self, owner):
        self.__owner = owner

    # We can overwrite functions in the super class
    def toString(self):
        return "{} is {} cm tall and {} kilograms and says {}. His owner is {}".format(self.get_name(), self.get_height(), self.get_weight(), self.get_sound(), self.__owner)
 
    # You don't have to require attributes to be sent
    # This allows for method overloading
    def multiple_sounds(self, how_many=None):
        if how_many is None:
            print(self.get_sound)
        else:
            print(self.get_sound() * how_many)

#+END_SRC

* Links
- [[http://www.newthinktank.com/2014/11/python-programming/][beginner cheat-sheet]]
- [[https://stackoverflow.com/questions/12179271/meaning-of-classmethod-and-staticmethod-for-beginner][SO classmethod]]
- [[https://github.com/zhiwehu/Python-programming-exercises/blob/master/100%2B%20Python%20challenging%20programming%20exercises.txt][Github exercises & solutions]]

* Exercises Level 1
- Question:Write a program which accepts a sequence of comma-separated numbers from console and generate a list and a tuple which contains every number.
- Question:
  Define a class which has at least two methods:
  getString: to get a string from console input
  printString: to print the string in upper case.
  Also please include simple test function to test the class methods.

* Exercise Level 2
- Question:
Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 * C * D)/H]
Following are the fixed values of C and H:
C is 50. H is 30.
D is the variable whose values should be input to your program in a comma-separated sequence.
Example
Let us assume the following comma separated input sequence is given to the program:
100,150,180
The output of the program should be:
18,22,24

Hints:
If the output received is in decimal form, it should be rounded off to its nearest value (for example, if the output received is 26.0, it should be printed as 26)
In case of input data being supplied to the question, it should be assumed to be a console input.


* Ideas??
